#!/usr/bin/env python3
"""
Report generator for the Heavy Quarkonium Spectroscopy pipeline.

Reads every CSV produced by ``run_spectrum.py`` in ``results/`` and assembles a
single, human-readable Markdown report (``REPORT.md`` at the project root) that
showcases the fitted parameters, the full mass spectra, the decay observables,
the radiative transitions and the global goodness-of-fit — all with their
propagated uncertainties and chi-square pulls.

Usage
-----
    conda run -n 400 python scripts/generate_report.py

Run ``run_spectrum.py`` first so the ``results/*.csv`` files exist.
"""

import os
import datetime
import pandas as pd
import numpy as np

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
RESULTS_DIR = os.path.join(ROOT, "results")
REPORT_PATH = os.path.join(ROOT, "REPORT.md")

# (sector_id, pretty sector name as used in the result filenames)
SECTORS = [
    ("bb", "Bottomonium (b_bbar)"),
    ("cc", "Charmonium (c_cbar)"),
    ("bc", "B_c Meson (b_cbar)"),
    ("cu", "D Meson (c_ubar)"),
]


# ---------------------------------------------------------------------------
# Small formatting helpers
# ---------------------------------------------------------------------------
def fmt(value, err=None, digits=4):
    """Format ``value ± err`` (or just ``value``) handling NaN/None gracefully."""
    try:
        v = float(value)
    except (TypeError, ValueError):
        return "—"
    if np.isnan(v):
        return "—"
    if err is None:
        return f"{v:.{digits}f}"
    try:
        e = float(err)
    except (TypeError, ValueError):
        e = 0.0
    if np.isnan(e):
        e = 0.0
    return f"{v:.{digits}f} ± {e:.{digits}f}"


def md_table(headers, rows):
    """Build a GitHub-flavoured Markdown table from headers and a list of rows."""
    out = ["| " + " | ".join(headers) + " |",
           "| " + " | ".join("---" for _ in headers) + " |"]
    for row in rows:
        out.append("| " + " | ".join(str(c) for c in row) + " |")
    return "\n".join(out)


def read_csv_safe(path):
    """Return a DataFrame or None if the file is missing/empty."""
    if not os.path.exists(path):
        return None
    try:
        return pd.read_csv(path)
    except Exception:
        return None


# ---------------------------------------------------------------------------
# Report sections
# ---------------------------------------------------------------------------
def section_header():
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    return (
        "# Heavy Quarkonium Spectroscopy — Results Report\n\n"
        f"_Auto-generated by `scripts/generate_report.py` on {now}._\n\n"
        "This report aggregates every CSV produced by `run_spectrum.py`. Masses are\n"
        "Gaussian-Expansion-Method (GEM) solutions of the Cornell potential with\n"
        "perturbative spin-dependent corrections; uncertainties are propagated from\n"
        "the fitted-parameter covariance, and the *pull* is\n"
        "`(calculated − experiment) / σ`.\n"
    )


def section_goodness_of_fit():
    df = read_csv_safe(os.path.join(RESULTS_DIR, "goodness_of_fit.csv"))
    lines = ["## 1. Global Goodness of Fit\n"]
    if df is None:
        lines.append("_`goodness_of_fit.csv` not found — run `run_spectrum.py` first._\n")
        return "\n".join(lines)

    rows = []
    tot_chi2 = 0.0
    tot_n = 0
    tot_par = 0
    for _, r in df.iterrows():
        n = int(r["n"])
        dof = int(r["dof"])
        rows.append([
            r["sector"],
            n,
            f"{r['chi2']:.2f}",
            dof,
            f"{r['chi2_per_dof']:.3f}",
            f"{r['rms_mev']:.2f}",
        ])
        tot_chi2 += r["chi2"]
        tot_n += n
        tot_par += n - dof
    glob_dof = max(tot_n - tot_par, 1)
    rows.append([
        "**GLOBAL**", tot_n, f"**{tot_chi2:.2f}**",
        tot_n - tot_par, f"**{tot_chi2 / glob_dof:.3f}**", "—",
    ])
    lines.append(md_table(
        ["Sector", "N states", "χ²", "dof", "χ²/dof", "RMS [MeV]"], rows))
    lines.append(
        "\n_χ²/dof ≲ 1 means the predictions agree with the PDG data within the "
        "propagated parameter uncertainties._\n")
    return "\n".join(lines)


def section_parameters():
    lines = ["## 2. Fitted Cornell Potential Parameters\n",
             "Potential: `V(r) = -(4/3) α_s / r + b·r + c`, with a Gaussian-smeared "
             "hyperfine contact term of width `σ`.\n"]
    rows = []
    for sid, _ in SECTORS:
        df = read_csv_safe(os.path.join(RESULTS_DIR, f"{sid}_params.csv"))
        if df is None or df.empty:
            continue
        r = df.iloc[0]
        chi2_cell = "—"
        if "chi2_per_dof" in df.columns and not pd.isna(r.get("chi2_per_dof")):
            chi2_cell = f"{float(r['chi2_per_dof']):.3f}"
        rows.append([
            sid.upper(),
            fmt(r["alpha_s"], r.get("err_alpha_s"), 4),
            fmt(r["b"], r.get("err_b"), 4),
            fmt(r["c"], r.get("err_c"), 4),
            fmt(r["sigma"], r.get("err_sigma"), 4),
            chi2_cell,
        ])
    lines.append(md_table(
        ["Sector", "α_s", "b [GeV²]", "c [GeV]", "σ [GeV]", "fit χ²/dof"], rows))
    lines.append(
        "\n_For the B_c sector `α_s` and `σ` are not fitted freely — they are "
        "log-interpolated from the cc/bb fits, and their uncertainties are inherited "
        "by error propagation._\n")
    return "\n".join(lines)


def _clean_state(name):
    """Strip the internal observable suffixes used as dict keys."""
    for suf in ("_rms", "_gg"):
        if name.endswith(suf):
            return name[: -len(suf)]
    return name


def section_masses():
    lines = ["## 3. Mass Spectra\n",
             "All `n^(2S+1)L_J` states with their propagated mass uncertainty. "
             "States without a PDG entry are model **predictions**.\n"]
    for sid, sname in SECTORS:
        df = read_csv_safe(os.path.join(RESULTS_DIR, f"{sname}_errors.csv"))
        if df is None or df.empty:
            continue
        lines.append(f"### {sname}\n")
        rows = []
        for _, r in df.iterrows():
            exp = r["Exp_GeV"]
            is_pred = str(exp) == "N/A" or pd.isna(exp)
            if is_pred:
                rows.append([
                    r["State"], fmt(r["Calculated_GeV"], r["Mass_Err_GeV"], 4),
                    "_pred._", "—", "—", "—",
                ])
            else:
                rows.append([
                    r["State"],
                    fmt(r["Calculated_GeV"], r["Mass_Err_GeV"], 4),
                    fmt(exp, None, 4),
                    f"{float(r['Abs_Err_MeV']):+.1f}",
                    f"{float(r['Pct_Err']):.3f}",
                    f"{float(r['Pull_sigma']):+.2f}",
                ])
        lines.append(md_table(
            ["State", "Calculated [GeV]", "Exp [GeV]", "Δ [MeV]", "% err", "pull σ"],
            rows))
        lines.append("")
    return "\n".join(lines)


def section_observables():
    """Annihilation/two-photon widths, cross-referenced with experiment."""
    lines = ["## 4. Decay Observables (annihilation & two-photon widths)\n"]

    # Pull experimental values + pulls from the consolidated report where present.
    cons = read_csv_safe(os.path.join(RESULTS_DIR, "consolidated_error_report.csv"))
    exp_lookup = {}
    if cons is not None:
        for _, r in cons.iterrows():
            if "Width" in str(r["Property"]):
                exp_lookup[(r["Sector"], str(r["State"]), str(r["Property"]))] = (
                    r.get("Experimental"), r.get("Pull_sigma"))

    for sid, sname in SECTORS:
        df = read_csv_safe(os.path.join(RESULTS_DIR, f"{sname}_observables.csv"))
        if df is None or df.empty:
            continue
        width_rows = []
        for _, r in df.iterrows():
            otype = str(r["Observable_Type"])
            if "Radius" in otype:
                continue  # RMS radii handled separately below
            state = _clean_state(str(r["State"]))
            exp, pull = exp_lookup.get((sid.upper(), str(r["State"]), otype), (None, None))
            # Skip forbidden/zero channels with no experimental counterpart
            # (e.g. spurious leptonic e+e- entries for P-wave triplets).
            has_exp = exp is not None and not pd.isna(exp)
            try:
                is_zero = abs(float(r["Value_keV"])) < 1e-6
            except (TypeError, ValueError):
                is_zero = False
            if is_zero and not has_exp:
                continue
            exp_cell = fmt(exp, None, 4) if exp is not None and not pd.isna(exp) else "—"
            pull_cell = (f"{float(pull):+.2f}"
                         if pull is not None and not pd.isna(pull) else "—")
            width_rows.append([
                state, otype.replace(" Width", ""),
                fmt(r["Value_keV"], r.get("Error_keV"), 4),
                exp_cell, pull_cell,
            ])
        if width_rows:
            lines.append(f"### {sname}\n")
            lines.append(md_table(
                ["State", "Channel", "Calc [keV]", "Exp [keV]", "pull σ"], width_rows))
            lines.append("")

    if len(lines) == 1:
        lines.append("_No annihilation widths available (neutral-flavour sectors only)._\n")
    return "\n".join(lines)


def section_rms_radii():
    lines = ["## 5. RMS Radii\n",
             "Root-mean-square radius `√⟨r²⟩` (GeV⁻¹) per state, with propagated "
             "uncertainty.\n"]
    any_data = False
    for sid, sname in SECTORS:
        df = read_csv_safe(os.path.join(RESULTS_DIR, f"{sname}_observables.csv"))
        if df is None or df.empty:
            continue
        rms = df[df["Observable_Type"].str.contains("Radius", na=False)]
        if rms.empty:
            continue
        any_data = True
        lines.append(f"### {sname}\n")
        rows = [[_clean_state(str(r["State"])), fmt(r["Value_keV"], r.get("Error_keV"), 3)]
                for _, r in rms.iterrows()]
        lines.append(md_table(["State", "√⟨r²⟩ [GeV⁻¹]"], rows))
        lines.append("")
    if not any_data:
        lines.append("_No RMS radius data found._\n")
    return "\n".join(lines)


def section_radiative():
    df = read_csv_safe(os.path.join(RESULTS_DIR, "radiative_decays.csv"))
    lines = ["## 6. Radiative Transitions (E1 & M1)\n"]
    if df is None or df.empty:
        lines.append("_`radiative_decays.csv` not found._\n")
        return "\n".join(lines)
    rows = []
    for _, r in df.iterrows():
        rows.append([
            r["Sector"], r["Type"], r["Transition"],
            fmt(r["Width_keV"], r.get("Width_err_keV"), 3),
        ])
    lines.append(md_table(["Sector", "Type", "Transition", "Width [keV]"], rows))
    lines.append("")
    return "\n".join(lines)


def section_highlights():
    """Best and worst agreements across all compared observables (by pull)."""
    cons = read_csv_safe(os.path.join(RESULTS_DIR, "consolidated_error_report.csv"))
    lines = ["## 7. Highlights\n"]
    if cons is None or cons.empty:
        lines.append("_Consolidated report not found._\n")
        return "\n".join(lines)

    df = cons.copy()
    df["abs_pull"] = pd.to_numeric(df["Pull_sigma"], errors="coerce").abs()
    df = df.dropna(subset=["abs_pull"])

    best = df.nsmallest(5, "abs_pull")
    worst = df.nlargest(5, "abs_pull")

    def rows_of(sub):
        return [[r["Sector"], r["State"], r["Property"],
                 f"{float(r['Pull_sigma']):+.2f}",
                 f"{float(r['Percentage_Error']):.2f}%"]
                for _, r in sub.iterrows()]

    lines.append("**Best agreement (smallest pull):**\n")
    lines.append(md_table(
        ["Sector", "State", "Property", "pull σ", "% err"], rows_of(best)))
    lines.append("\n**Largest tension (biggest pull):**\n")
    lines.append(md_table(
        ["Sector", "State", "Property", "pull σ", "% err"], rows_of(worst)))
    lines.append("")
    return "\n".join(lines)


def main():
    if not os.path.isdir(RESULTS_DIR):
        raise SystemExit(
            f"results/ directory not found at {RESULTS_DIR}. "
            "Run scripts/run_spectrum.py first.")

    sections = [
        section_header(),
        section_goodness_of_fit(),
        section_parameters(),
        section_masses(),
        section_observables(),
        section_rms_radii(),
        section_radiative(),
        section_highlights(),
        "\n---\n_End of report._\n",
    ]
    report = "\n\n".join(sections)

    with open(REPORT_PATH, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"Report written to {REPORT_PATH}")


if __name__ == "__main__":
    main()
